import { CourseFacts } from '../types';

export const COURSE_FACTS: CourseFacts[] = [
  {
    courseCode: 'OBGMD',
    courseName: 'OBGYN MD (Residency + Super Speciality)',
    segment: 'PG',
    dataQuality: 'strong — three independent brochure/leaflet sources agree line-for-line',
    chiefEditor: {
      name: 'Dr Aswath Kumar',
      credentials: 'MD, FICOG',
      designation: 'Professor, Department of Gynecology, Jubilee Mission Medical College, Thrissur, Kerala',
      spellingConfidence: 'disputed',
      conflict: true,
      conflictDetail: "Disputed between 'Dr Aswath Kumar' and 'Dr. Ashwani' in internal training notes. Omit chief editor name until confirmed.",
    },
    facultyNames: [
      { name: 'Dr Aswath Kumar', role: 'Chief Editor; Section Editor — Gynecologic Oncology', spellingConfidence: 'disputed' },
      { name: 'Dr S Krishnakumar', role: 'Section Editor — Hysteroscopy', spellingConfidence: 'disputed' },
      { name: 'Dr B Ramesh', role: 'Section Editor — Laparoscopy', spellingConfidence: 'confirmed' },
      { name: 'Dr Prasanth PK', role: 'Section Editor — Fetal Medicine', spellingConfidence: 'confirmed' },
      { name: 'Dr Venugopal M', role: 'Section Editor — Reproductive Endocrinology', spellingConfidence: 'confirmed' },
      { name: 'Dr Sonal Panchal', role: 'Section Editor — Ultrasound', spellingConfidence: 'confirmed' },
      { name: 'Dr Dinesh Thomas Cherian', role: 'Section Editor — Urogynecology', spellingConfidence: 'confirmed' },
      { name: 'Dr Richa Saxena', role: 'Section Editor — Medical Statistics', spellingConfidence: 'confirmed' },
    ],
    referenceTextbook: [
      'Williams Obstetrics (Obstetrics core)',
      "Berek & Novak's Gynecology (Gynecology core)",
      'DiSaia and Creasman Clinical Gynecologic Oncology',
      "Speroff's Clinical Gynecologic Endocrinology and Infertility",
      "Callen's Ultrasonography in Obstetrics & Gynecology",
    ],
    priceCurrent: '₹24,999 (12 months)',
    priceStruck: null,
    priceNotes: 'List price ₹24,999 (12 months). Printed notes sold separately at ₹3,499.',
    curriculumHighlights: [
      '7 focused superspeciality modules: Gynecologic Oncology, Urogynecology, Reproductive Endocrinology, Hysteroscopy, Ultrasound, Laparoscopy, Medical Statistics',
      '200+ structured OSCE stations for practical/DNB case handling',
      'DxTx — diagnosis-and-treatment pathways for 145+ key topics, NMC-curriculum aligned',
      '339+ entry drug formulary including safety in pregnancy and lactation',
      'Two MRCOG mock papers bundled inside the course',
      'Operative Procedures in OBGYN — difficult procedures explained through real-time surgical video',
      'Dr. Wise AI companion trained on faculty-reviewed Jaypee material',
    ],
    approvedClaims: [
      { claim: '285+ hrs of Video Lectures', locator: 'Course Features tile', conflict: false },
      { claim: '420+ Topics in Videos', locator: 'Course Features tile', conflict: false },
      { claim: '325+ Topics in Notes', locator: 'Lecture Notes tile', conflict: false },
      { claim: '6,000+ Questions in QBank', locator: 'QBank tile', conflict: false },
      { claim: '200+ OSCEs', locator: 'OSCE tile', conflict: false },
      { claim: '528+ Key References', locator: 'Key References tile', conflict: false },
      { claim: '145+ DxTx', locator: 'DxTx tile', conflict: false },
      { claim: '339+ Drug Chart', locator: 'Drug Chart tile', conflict: false },
      { claim: '25+ live case discussion videos', locator: 'Clinical Case-Based Discussion', conflict: false },
      { claim: '7 superspeciality modules', locator: 'Brochure Cover', conflict: false },
      { claim: '73 high-yield videos, built directly from past NEET-SS exam questions', locator: 'Refresher Notes', conflict: false },
      { claim: '2 MRCOG mock papers included', locator: 'Inclusions list', conflict: false },
      { claim: '55+ years — Jaypee Brothers Medical Publishers', locator: 'About DigiNerve', conflict: false, scope: 'brand-level' },
      { claim: '₹24,999 (12 months, list price)', locator: 'Pricing schedule', conflict: false },
    ],
    testimonials: [
      {
        quote: 'The OSCE was particularly valuable for last-minute revision.',
        attribution: 'Dr Sajal Das, DNB Resident, Tata Main Hospital, Jamshedpur',
        rightsStatus: 'UNCONFIRMED — Confirm permission before use',
      },
    ],
    competitorContrast: [
      { claim: '285+ hrs vs ~280 hrs (video lectures) on typical alternative platform' },
      { claim: '6,000+ MCQs vs ~1,440 on typical alternative platform' },
      { claim: '200+ OSCE case scenarios vs Not offered on alternative platforms' },
      { claim: '₹24,999 vs ₹41,999 (12-month list price on typical alternative platform)' },
    ],
    cautions: [
      "Chief editor's name is DISPUTED (Aswath Kumar vs Ashwani). Do not put the name in any ad until Content confirms.",
      'Faculty count is DISPUTED (104 brochure vs 98 site FAQ). Do not use a faculty count.',
      "Never name Marrow. The comparison column must read 'typical alternative platform'.",
      'Do not imply the course awards an MD qualification.',
      'The 2 MRCOG mock papers are bundled inside OBGYN MD — do not describe as a standalone free download.',
    ],
  },
  {
    courseCode: 'PEDMD',
    courseName: 'Pediatrics MD (Residency + NEET-SS)',
    segment: 'PG',
    dataQuality: 'medium — numbers corroborated across explainer and past ads',
    chiefEditor: {
      name: 'Dr Piyush Gupta',
      credentials: 'MD (former Head of Paediatrics, UCMS Delhi)',
      spellingConfidence: 'confirmed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Dr Piyush Gupta', role: 'Chief Editor / Academic Director', spellingConfidence: 'confirmed' },
      { name: 'Dr Prerna Batra', role: 'Live Class Educator', spellingConfidence: 'unknown' },
      { name: 'Dr S Adithya', role: 'Live Class Educator', spellingConfidence: 'unknown' },
      { name: 'Dr Vishal Saini', role: 'Live Class Educator', spellingConfidence: 'unknown' },
    ],
    referenceTextbook: ["Nelson's Textbook of Pediatrics", "Dr Piyush Gupta's Postgraduate Pediatrics"],
    priceCurrent: '₹24,999 (12 months)',
    priceStruck: null,
    curriculumHighlights: [
      'Past university exam questions embedded directly inside video lectures',
      'Pediatric drug-dosing chart calibrated to child weight and age',
      'Case-based clinical discussion module covering long and short cases',
      'OSCEs tailored for MD and DNB pediatric candidates',
      'Dr. Wise AI chatbot drawing on 30+ reference books including 12 IAP publications',
      'NEET-SS recall questions embedded in SS-track videos',
    ],
    approvedClaims: [
      { claim: '245+ hours of video lectures', locator: 'Supplied Ad & Explainer', conflict: false },
      { claim: '5,600+ QBank questions', locator: 'Supplied Ad & Explainer', conflict: false },
      { claim: '320+ notes', locator: 'Explainer Inclusions', conflict: false },
      { claim: '₹24,999 for 12 months', locator: 'Price schedule', conflict: false },
    ],
    competitorContrast: [
      { claim: "Marrow's Paediatrics SS-only course is ₹41,999 — DigiNerve is roughly half, with broader coverage", publicUseNote: "Use 'typical alternative platform'" },
    ],
    cautions: [
      "The course is mid-restructure into Residency, SS, and Live Classes. Use 'Live Classes', never write 'Chat Shows' for Pediatrics.",
      'OSCEs are NOT included in the standalone SS track. Never claim OSCEs for the SS product alone.',
      "No named Pediatrics learner testimonial exists in verified sources. Do not fabricate one.",
      "'MD, FRCPCH' for Dr Piyush Gupta is unverified derived ad text — do not print FRCPCH.",
    ],
  },
  {
    courseCode: 'OPHMD',
    courseName: 'Ophthalmology MD (Residency + Super Speciality) — V2.0 revamp',
    segment: 'PG',
    dataQuality: 'thin on product numbers, strong on faculty credentials',
    chiefEditor: {
      name: 'Dr N. Venkatesh Prajna',
      credentials: 'Aravind Eye Care System, Madurai',
      spellingConfidence: 'disputed',
      conflict: true,
      conflictDetail: "Weight of evidence favors Dr N. Venkatesh Prajna (Aravind Eye Care System), but handwritten notes cited 'Dr Prajakta'. Confirm internally before print.",
    },
    facultyNames: [
      { name: 'Dr N. Venkatesh Prajna', role: 'Chief Editor', spellingConfidence: 'disputed' },
      { name: 'Dr Jitendra Jethani', role: 'Co-presenter Live Class', spellingConfidence: 'unknown' },
    ],
    referenceTextbook: {
      value: "Peyman's Principles and Practice of Ophthalmology",
      conflict: true,
      conflictDetail: "Conflict between Peyman's (sales deck) and Parsons' (PM notes). Confirm before using in copy.",
    },
    priceCurrent: null,
    priceStruck: null,
    priceNotes: 'NO PRICE may be advertised from local sources. Pricing ladder pending publication.',
    curriculumHighlights: [
      'Repositioned across MD residency track and SS super-speciality track',
      'Videos organised topic-wise',
      'DxTx quick-reference ready-reckoner',
      'Drug formulary covering drugs A to Z',
      'Chat shows and live case discussions built into course modules',
      'Clinical Pulse — OPD evaluation and quick topic recaps',
    ],
    approvedClaims: [
      { claim: '210+ hours of video lectures', locator: 'Ad Creative & Explainer', conflict: false },
      { claim: '55+ contributor faculty pool', locator: 'Deck Faculty Roster', conflict: false },
    ],
    testimonials: [
      {
        quote: 'The lectures are clear, while Clinical Pulse provides useful OPD evaluation and quick topic recaps.',
        attribution: 'Dr Mansi Jain, Moti Lal Nehru Medical College, Prayagraj',
        rightsStatus: 'Quote appeared in supplied ad — confirm final wording',
      },
    ],
    competitorContrast: [],
    cautions: [
      'NO PRICE may be advertised — none is recorded in verified local sources.',
      'NO QBANK NUMBER may be advertised. Supplied ads disagree on QBank totals.',
      "Reference textbook is in active conflict (Peyman's vs Parsons'). Do not print textbook name until confirmed.",
      'Do not print credentials for Dr Prajna without primary verification.',
    ],
  },
  {
    courseCode: 'ANESMD',
    courseName: 'Anesthesiology and Critical Care MD (Residency + NEET SS)',
    segment: 'PG',
    dataQuality: 'strong — live course page capture and deck summaries agree',
    chiefEditor: {
      name: 'Dr Jigeeshu V. Divatia and Dr Atul P. Kulkarni',
      spellingConfidence: 'disputed',
      conflict: true,
      conflictDetail: "CRITICAL: 'Late Dr Atul P Kulkarni' appears on two decks; live site omits 'Late'. Do NOT name Dr Kulkarni until content confirms.",
    },
    facultyNames: [
      { name: 'Dr. Jigeeshu V. Divatia', role: 'Chief Editor — Anesthesia', spellingConfidence: 'confirmed' },
      { name: 'Dr. Atul P. Kulkarni', role: 'Chief Editor — Anesthesia', spellingConfidence: 'disputed' },
    ],
    referenceTextbook: "Miller's Anesthesia",
    priceCurrent: '₹24,999.00 (12 Months)',
    priceStruck: null,
    curriculumHighlights: [
      'Practical system-oriented approach spanning MD exams and NEET-SS preparation',
      '200+ NEET SS Recalls — previous NEET-SS questions collected for prep',
      'Interactive drug formulary with risk-based classification',
      'Objective clinical skills assessment and revision (OSCEs / simulated scenarios)',
      'Mocks, minis and subject tests with in-depth performance analysis',
      'Emergency drug-dosing charts',
      'Dr. Wise AI chatbot powered by Jaypee textbooks',
    ],
    approvedClaims: [
      { claim: '130+ Hrs of Video Lectures', locator: "What You'll Get tile", conflict: false },
      { claim: '190+ Topics in Videos & Notes', locator: "What You'll Get tile", conflict: false },
      { claim: '3200+ Questions in QBank', locator: "What You'll Get tile", conflict: false },
      { claim: '200+ NEET SS Recalls', locator: "What You'll Get tile", conflict: false },
      { claim: '380+ benchmark-trial summaries', locator: 'Explainer Deck', conflict: false },
      { claim: '380+ key references', locator: 'Explainer Deck', conflict: false },
      { claim: '₹24,999.00 for 12 Months', locator: 'Live Course Page', conflict: false },
    ],
    competitorContrast: [
      { claim: 'Marrow ₹41,999; UK-linked competitor ₹82,500 vs DigiNerve ₹24,999', publicUseNote: "Use 'typical alternative platform'" },
    ],
    cautions: [
      "HIGHEST RISK: Discrepancy between 'Late Dr Atul P Kulkarni' and 'Dr Atul P Kulkarni'. Never name Dr Kulkarni until Content confirms.",
      "Site spelling is 'Anesthesiology' (not 'Anaesthesiology'). Match the site.",
      'Printed Notes tier (₹4,124) is FOR EXISTING SUBSCRIBERS ONLY — do not advertise as an open price.',
      'Expired Freedom Fest discount must never be referenced.',
    ],
  },
  {
    courseCode: 'MEDMD',
    courseName: 'Medicine MD (Residency + NEET-SS)',
    segment: 'PG',
    dataQuality: 'medium — single-sourced to deck summary',
    chiefEditor: {
      name: 'Dr. Jyotirmoy Pal, Dr. Archith Boloor, Dr. Shashank Joshi (Joint Lead Faculty)',
      spellingConfidence: 'confirmed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Dr. Archith Boloor', role: 'Faculty — Internal Medicine', spellingConfidence: 'confirmed' },
      { name: 'Dr. Jyotirmoy Pal', role: 'Faculty', spellingConfidence: 'unknown' },
      { name: 'Dr. Shashank Joshi', role: 'Faculty', spellingConfidence: 'unknown' },
    ],
    referenceTextbook: "Harrison's Principles of Internal Medicine",
    priceCurrent: '₹24,999 for 12 months',
    priceStruck: null,
    curriculumHighlights: [
      'Covers MD General Medicine residency syllabus and NEET-SS prep for Cardiology / Nephrology / Gastroenterology tracks',
      'Drug reference guide and clinical pathways',
      "'Dr. Wise' AI study assistant",
      'Live doubt-clearing sessions and high-yield mocks',
    ],
    approvedClaims: [
      { claim: '425+ hours of video', locator: 'Explainer Deck', conflict: false },
      { claim: '12,680+ practice questions', locator: 'Explainer Deck', conflict: false },
      { claim: '770+ topic notes', locator: 'Explainer Deck', conflict: false },
      { claim: '₹24,999 for 12 months', locator: 'Explainer Deck', conflict: false },
    ],
    competitorContrast: [
      { claim: 'Marrow equivalent costs ₹44,999 — DigiNerve is roughly half price with more hours and AI assistant', publicUseNote: "Use 'typical alternative platform'" },
    ],
    cautions: [
      'No single chief editor designated; do not title any faculty as Chief Editor.',
      'Never name Marrow.',
    ],
  },
  {
    courseCode: 'SURGSS',
    courseName: 'Surgery MS — Residency + NEET-SS + INI-SS (V2.0)',
    segment: 'PG',
    dataQuality: 'strong on features, deck corroborated by catalog captures',
    chiefEditor: {
      name: 'Prof. Dr Nilay Mandal',
      credentials: 'Calcutta National Medical College and Hospital, Kolkata',
      spellingConfidence: 'confirmed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Prof. Dr Nilay Mandal', role: 'Lead faculty / Chief Editor', spellingConfidence: 'confirmed' },
      { name: 'Dr Sunil Shenvi', role: 'GI/HPB/Multiorgan Transplant Surgery', spellingConfidence: 'confirmed' },
      { name: 'Dr Shouptik Basu', role: 'Surgical Oncology, MCh AIIMS', spellingConfidence: 'disputed' },
      { name: 'Dr Rahul Jain', role: 'Neurosurgery, MCh AIIMS', spellingConfidence: 'unknown' },
    ],
    referenceTextbook: [
      "Bailey & Love's Short Practice of Surgery",
      "Sabiston's Textbook of Surgery",
      "Schwartz's Principles of Surgery",
    ],
    priceCurrent: '₹29,999 for 12 months',
    priceStruck: null,
    curriculumHighlights: [
      '200+ OSCEs and practical case scenarios',
      '100+ SxTools surgical-instrument flashcards',
      '1,260+ benchmark-trial summaries',
      '250+ DxTx entries and 450+ surgical tips',
      'NEET-SS recall videos (2021-2023) with expert analysis',
      '3-volume printed notes companion',
    ],
    approvedClaims: [
      { claim: '460+ hours of video', locator: 'Explainer Deck', conflict: false },
      { claim: '630+ topics', locator: 'Explainer Deck', conflict: false },
      { claim: '10,400+ MCQs in the QBank', locator: 'Explainer Deck', conflict: false },
      { claim: '200+ OSCEs', locator: 'Explainer Deck', conflict: false },
      { claim: '1,260+ benchmark-trial summaries', locator: 'Explainer Deck', conflict: false },
      { claim: '250+ DxTx entries', locator: 'Explainer Deck', conflict: false },
      { claim: '100+ SxTools surgical-instrument flashcards', locator: 'Explainer Deck', conflict: false },
      { claim: '450+ surgical tips', locator: 'Explainer Deck', conflict: false },
      { claim: '₹29,999 for 12 months', locator: 'Confirmed Deck', conflict: false },
    ],
    competitorContrast: [
      { claim: 'No alternative platform offers OSCEs, benchmark trials, DxTx, SxTools, and Dr. Wise at any price' },
    ],
    cautions: [
      'Do NOT claim lowest price — RAA Online is listed at ₹20,000 against DigiNerve ₹29,999.',
      '₹24,999 is a superseded figure for Surgery MS; use ₹29,999.',
      'Never name competitors in public copy.',
    ],
  },
  {
    courseCode: 'ORTHMS',
    courseName: 'Orthopedics MS — Residency + Super Speciality (V2.0)',
    segment: 'PG',
    dataQuality: 'strong on features, confirmed V2.0 deck',
    chiefEditor: {
      name: 'Dr Vivek Pandey',
      credentials: 'Professor and Unit Head, Dept of Orthopaedic Surgery, KMC Manipal; Author of Manipal Manual of Orthopaedics',
      spellingConfidence: 'confirmed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Dr Vivek Pandey', role: 'Chief Editor', spellingConfidence: 'confirmed' },
      { name: 'Dr Abhijeet L. Wahegaonkar', role: 'Mentor (Hand & Upper Limb)', spellingConfidence: 'unknown' },
      { name: 'Dr Rajiv Shah', role: 'Mentor (Foot & Ankle)', spellingConfidence: 'unknown' },
      { name: 'Dr Kaustubh Belapurkar', role: 'Mentor (Joint Replacement & Sports)', spellingConfidence: 'unknown' },
    ],
    referenceTextbook: [
      'Essential Orthopedics: Principles and Practice (Dr Manish Kumar Varshney)',
      "Campbell's Operative Orthopaedics",
    ],
    priceCurrent: '₹24,999 for 12 months',
    priceStruck: null,
    curriculumHighlights: [
      'Super Speciality QBank spanning Sports Medicine, Pediatric Orthopedics, Spine, Hand Surgery, Arthroscopy',
      '430+ OSCEs and 2,000+ previous-year university questions',
      'Ganga Video Atlas of Spine Surgery module (new in V2.0)',
      'Dedicated Implants module and surgical flashcards',
      "Printed notes and 'Dr. Wise' AI chatbot",
    ],
    approvedClaims: [
      { claim: '265+ hours of video', locator: 'V2.0 Deck', conflict: false },
      { claim: '575+ topics', locator: 'V2.0 Deck', conflict: false },
      { claim: '430+ OSCEs', locator: 'V2.0 Deck', conflict: false },
      { claim: '1,100+ benchmark trials', locator: 'V2.0 Deck', conflict: false },
      { claim: '120+ DxTx entries', locator: 'V2.0 Deck', conflict: false },
      { claim: '120+ drug-chart entries', locator: 'V2.0 Deck', conflict: false },
      { claim: '2,000+ previous-year university questions', locator: 'V2.0 Deck', conflict: false },
      { claim: '9+ high-yield-question videos', locator: 'V2.0 Deck', conflict: false },
      { claim: '₹24,999 for 12 months', locator: 'V2.0 Deck', conflict: false },
    ],
    competitorContrast: [],
    cautions: [
      "Orthopaedics has NO standalone NEET-SS DM/MCh pathway. 'Crack super-speciality exam' framing is factually wrong; post-MS specialisation happens via FNB/international fellowships.",
      'Do not claim lowest price.',
      'The 5,750+ QBank total does not reconcile with the 2,100+/1,500+ split — omit QBank claim.',
    ],
  },
  {
    courseCode: 'DERMD',
    courseName: 'Dermatology MD (Residency) — Dermatology, Venereology & Leprosy',
    segment: 'PG',
    dataQuality: 'strong — verified dedicated build prompt facts table',
    chiefEditor: {
      name: 'Dr Rashmi Sarkar and Dr S. Sacchidanand (Co-Chief Editors)',
      spellingConfidence: 'confirmed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Dr Rashmi Sarkar', role: 'Co-Chief Editor', spellingConfidence: 'confirmed' },
      { name: 'Dr S. Sacchidanand', role: 'Co-Chief Editor', spellingConfidence: 'confirmed' },
      { name: 'Koushik Lahiri', role: 'Author of the reference textbook', spellingConfidence: 'confirmed' },
    ],
    referenceTextbook: 'Postgraduate Dermatology by Koushik Lahiri — a Jaypee title',
    priceCurrent: '₹14,999 (12 months)',
    priceStruck: null,
    curriculumHighlights: [
      '775+ OSCE flashcards with real clinical photographs and histopathology slides',
      '945+ practice questions, every one thoroughly explained',
      'Colour-coded drug guide and dermatological formulary',
      'Dr. Wise AI clinical companion',
      'Live interactive classes with specialty faculty',
    ],
    approvedClaims: [
      { claim: '108+ hours of video', locator: 'Confirmed Facts Table', conflict: false },
      { claim: '180+ topics', locator: 'Confirmed Facts Table', conflict: false },
      { claim: '945+ practice questions with explanations', locator: 'Confirmed Facts Table', conflict: false },
      { claim: '775+ image flashcards, clinical & histopath', locator: 'Confirmed Facts Table', conflict: false },
      { claim: '340+ key references', locator: 'Confirmed Facts Table', conflict: false },
      { claim: '78 contributing faculty', locator: 'Confirmed Facts Table', conflict: false },
      { claim: '₹14,999', locator: 'Confirmed Facts Table', conflict: false },
      { claim: 'Printed notes ₹3,499', locator: 'Confirmed Facts Table', conflict: false },
    ],
    competitorContrast: [
      { claim: "Alternative platform equivalent ₹24,999 against DigiNerve's ₹14,999" },
    ],
    cautions: [
      'Dermatology, Venereology & Leprosy is a TERMINAL MD in India. There is NO NEET-SS route. Any NEET-SS or MRCOG reference is factually wrong.',
      'Do not lead with video hours — 108+ is the lowest in the postgrad catalog.',
      'Price is deliberately not displayed on the landing page; check with CRO before putting in an ad.',
    ],
  },
  {
    courseCode: 'SURGONC',
    courseName: 'Surgical Oncology (for SS)',
    segment: 'PG',
    dataQuality: 'medium — deck summary corroborated by live catalog card',
    chiefEditor: {
      name: 'Dr. Shouptik Basu',
      credentials: 'MCh Surgical Oncology, AIIMS',
      spellingConfidence: 'disputed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Dr. Shouptik Basu', role: 'Chief Editor', spellingConfidence: 'disputed' },
      { name: 'Dr. Sunil Shenvi', role: 'Theory Faculty', spellingConfidence: 'confirmed' },
    ],
    referenceTextbook: ['Bailey & Love', 'Sabiston', 'DeVita, Hellman, and Rosenberg’s Cancer'],
    priceCurrent: '₹9,999.00 (6 Months)',
    priceStruck: null,
    curriculumHighlights: [
      '500+ landmark-trial summaries',
      '250+ topic notes',
      'AI clinical oncology study assistant',
      'Positioned as a distilled high-yield alternative to reading DeVita end to end',
    ],
    approvedClaims: [
      { claim: '220+ hours of video', locator: 'Deck Inclusions', conflict: false },
      { claim: '1,100+ questions', locator: 'Deck Inclusions', conflict: false },
      { claim: '250+ topic notes', locator: 'Deck Inclusions', conflict: false },
      { claim: '500+ landmark-trial summaries', locator: 'Deck Inclusions', conflict: false },
      { claim: '6mo ₹9,999 · 12mo ₹14,999 · 18mo ₹18,999 · 24mo ₹23,999', locator: 'Price Ladder', conflict: false },
    ],
    competitorContrast: [
      { claim: 'Marrow does not run a dedicated Surgical Oncology course at all — a genuine DigiNerve exclusive in this niche' },
    ],
    cautions: [
      "Do NOT use the word 'guarantee' in copy without Legal sign-off.",
      'Do not name DeVita in a way that implies endorsement by or affiliation with the textbook publisher.',
      'Never name Marrow.',
    ],
  },
  {
    courseCode: 'NEUROSS',
    courseName: 'Neurosurgery (for SS)',
    segment: 'PG',
    dataQuality: 'medium — single source deck summary',
    chiefEditor: {
      name: 'Dr. Sunil Shenvi and Dr. Rahul Jain',
      spellingConfidence: 'confirmed',
      conflict: true,
      conflictDetail: 'Dr Rahul Jain is an AIIMS-trained neurosurgeon; confirm faculty lead with Content before naming.',
    },
    facultyNames: [
      { name: 'Dr. Sunil Shenvi', role: 'Chief Editor', spellingConfidence: 'confirmed' },
      { name: 'Dr. Rahul Jain', role: 'Section Editor — AIIMS-trained neurosurgeon', spellingConfidence: 'unknown' },
    ],
    referenceTextbook: "Youmans & Winn Neurological Surgery",
    priceCurrent: '₹10,999 (12 months)',
    priceStruck: null,
    curriculumHighlights: [
      '180+ topics tailored for the tightest-cutoff super-speciality in India',
      '360+ landmark trials',
      'Built on six named neurosurgery reference textbooks',
    ],
    approvedClaims: [
      { claim: '155+ hours of video', locator: 'Explainer Deck', conflict: false },
      { claim: '1,000 questions', locator: 'Explainer Deck', conflict: false },
      { claim: '180+ topics', locator: 'Explainer Deck', conflict: false },
      { claim: '360+ landmark trials', locator: 'Explainer Deck', conflict: false },
      { claim: '12mo ₹10,999', locator: 'Price', conflict: false },
    ],
    competitorContrast: [
      { claim: 'Marrow has no dedicated Neurosurgery course; closest alternative charges over 4x DigiNerve price' },
    ],
    cautions: [
      "Do NOT use NEET-SS cutoff statistics (AIR ~67–112) in ad copy — reads as discouraging.",
      "'1,000 questions' has NO plus sign in verified source — do not render as '1,000+'.",
    ],
  },
  {
    courseCode: 'MRCOG',
    courseName: 'Cracking MRCOG (6 live variants: Part 1/2/3 × Comprehensive/Crash/Live-OSCE/Non-Interactive)',
    segment: 'PROF',
    dataQuality: 'prices strong from live catalog; self-paced and recorded modules',
    chiefEditor: {
      name: 'Dr. Richa Saxena',
      role: 'Named Faculty on all six MRCOG variants',
      spellingConfidence: 'confirmed',
      conflict: false,
    },
    facultyNames: [
      { name: 'Dr. Richa Saxena', role: 'Lead Faculty', spellingConfidence: 'confirmed' },
    ],
    priceCurrent: '₹24,999 to ₹34,999 across variants',
    priceStruck: null,
    curriculumHighlights: [
      'Six product variants across Part 1, Part 2 and Part 3 (Comprehensive, Crash, Live-OSCE, Non-Interactive)',
      'Self-paced, high-yield recorded modular structure',
    ],
    approvedClaims: [
      { claim: 'Cracking MRCOG - Part 1 - Comprehensive: ₹29,999.00, 6 Months', locator: 'Live Catalog', conflict: false },
      { claim: 'Cracking MRCOG - Part 1 - Crash: ₹24,999.00, 3 Months', locator: 'Live Catalog', conflict: false },
      { claim: 'Cracking MRCOG - Part 2 - Comprehensive: ₹34,999.00, 6 Months', locator: 'Live Catalog', conflict: false },
      { claim: 'Cracking MRCOG Part 2 - Crash: ₹29,999.00, 3 Months', locator: 'Live Catalog', conflict: false },
      { claim: 'Cracking MRCOG - Part 3 – Live: ₹32,999.00, 2 Months', locator: 'Live Catalog', conflict: false },
      { claim: 'Cracking MRCOG - Part 3 – Non-Interactive: ₹27,999.00, 2 Months', locator: 'Live Catalog', conflict: false },
      // Part 1 Crash Course only (diginerve.com course page, checked 24-Sep-2026). Never reuse on other variants.
      { claim: '171 bite-sized video lectures', locator: 'Course page, Part 1 Crash Course', conflict: false, scope: 'MRCOG Part 1 Crash' },
      { claim: '8+ hrs of video lectures', locator: 'Course page, Part 1 Crash Course', conflict: false, scope: 'MRCOG Part 1 Crash' },
      { claim: '1,500 interactive flashcards', locator: 'Course page, Part 1 Crash Course', conflict: false, scope: 'MRCOG Part 1 Crash' },
      { claim: '5 mock exam sets, 1,000 questions', locator: 'Course page, Part 1 Crash Course', conflict: false, scope: 'MRCOG Part 1 Crash' },
      { claim: '170+ lecture notes', locator: 'Course page, Part 1 Crash Course', conflict: false, scope: 'MRCOG Part 1 Crash' },
      { claim: 'Supported with RCOG and UK guidelines', locator: 'Course page, Part 1 Crash Course', conflict: false, scope: 'MRCOG Part 1 Crash' },
      // Part 1 Comprehensive only (course page checked 25-Sep-2026; books + PYQs confirmed by Mehul). Never reuse on other variants.
      { claim: '80+ hrs of video lectures', locator: 'Course page, Part 1 Comprehensive', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: '37+ hrs of question discussion', locator: 'Course page, Part 1 Comprehensive', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: '2,630+ single-best answers', locator: 'Course page, Part 1 Comprehensive (feature card)', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: '1,000+ flashcards', locator: 'Course page, Part 1 Comprehensive (6 & 12-month plans)', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: '10 sets of mock exams, 20 practice papers', locator: 'Course page, Part 1 Comprehensive', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: '70+ benchmark trials', locator: 'Course page, Part 1 Comprehensive', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: "Dr Richa's MRCOG Part 1 book (3rd edition), printed and delivered", locator: 'Course page + Mehul, 25-Sep-2026', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: '5 years of PYQs discussed', locator: 'Mehul, 25-Sep-2026', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
      { claim: 'GTG guidelines covered', locator: 'Course page, Part 1 Comprehensive', conflict: false, scope: 'MRCOG Part 1 Comprehensive' },
    ],
    competitorContrast: [],
    cautions: [
      "NO LIVE-COHORT FRAMING: Never write 'join us on [date]', no batch dates, no live session references. Modules are recorded & self-paced.",
      "Always state the EXACT variant name (e.g. 'Part 2 — Crash Course'), never just 'Cracking MRCOG'.",
      'Never advertise one variant price against another variant name.',
    ],
  },
];

export function getCourseByCode(code: string): CourseFacts | undefined {
  return COURSE_FACTS.find((c) => c.courseCode === code);
}
