export const TAXONOMY = {
  BRAND: ['DN', 'JP', 'RAS'] as const,
  TYPE: ['LEADS', 'CHATSHOW', 'SALES', 'WA', 'APP', 'RMK', 'BRAND'] as const,
  PLATFORM: ['META', 'GOOG', 'YT', 'WA', 'EM', 'SMS', 'INF', 'ORG', 'OFF'] as const,
  OBJECTIVE: [
    'INSTANTFORM',
    'LP',
    'CTWA',
    'APPINSTALL',
    'VIDEO',
    'SEARCH',
    'PMAX',
    'DISPLAY',
    'DEMANDGEN',
  ] as const,
  SEGMENT: ['UG', 'PG', 'INT', 'FMGE', 'PROF', 'NURS', 'DENT'] as const,
  PRODUCT: [
    'MEDMD',
    'ORTHMS',
    'OPHMD',
    'DERMD',
    'OBGMD',
    'PEDMD',
    'ANESMD',
    'SURGSS',
    'NEUROSS',
    'SURGONC',
    'DIGINEET',
    'DIGIONE',
    'DIGIFMGE',
    'MRCOG',
    'BOOK',
  ] as const,
  GEO: ['IN', 'INN', 'INS', 'INE', 'INW', 'INXN', 'INTL'] as const,
  TARGETING: ['INT', 'LAL', 'CUS', 'OPEN', 'ADV', 'DATA', 'RMK'] as const,
  FORMAT: ['IMG', 'VID', 'CAR', 'COL', 'RSA', 'DCO'] as const,
  ANGLE: [
    'FACULTY',
    'RESULT',
    'DEMO',
    'PRICE',
    'URGENCY',
    'SOCIAL',
    'FREE',
    'CURRICULUM',
  ] as const,
  OFFER: ['FLAT40', 'FLAT30', 'FREETRIAL', 'FEST', 'LAUNCH', 'NOOFFER'] as const,
} as const;

export const PRODUCT_LABELS: Record<string, string> = {
  OBGMD: 'OBGYN MD (Residency + Super Speciality)',
  PEDMD: 'Pediatrics MD (Residency + NEET-SS)',
  OPHMD: 'Ophthalmology MD (Residency + Super Speciality)',
  ANESMD: 'Anesthesiology & Critical Care MD',
  MEDMD: 'Medicine MD (Residency + NEET-SS)',
  SURGSS: 'Surgery MS (Residency + NEET-SS)',
  ORTHMS: 'Orthopedics MS (Residency + Super Speciality)',
  DERMD: 'Dermatology MD (DVL Residency)',
  SURGONC: 'Surgical Oncology (for SS)',
  NEUROSS: 'Neurosurgery (for SS)',
  MRCOG: 'Cracking MRCOG (Parts 1/2/3)',
  DIGINEET: 'DigiNEET PG Core',
  DIGIONE: 'DigiOne Medical Pass',
  DIGIFMGE: 'DigiFMGE Comprehensive',
  BOOK: 'Jaypee Clinical Textbook Editions',
};

export const GEO_LABELS: Record<string, string> = {
  IN: 'India (National All)',
  INN: 'India North',
  INS: 'India South',
  INE: 'India East',
  INW: 'India West',
  INXN: 'India (Excluding North)',
  INTL: 'International / NRI',
};

export const TARGETING_LABELS: Record<string, string> = {
  INT: 'Interest / Demographics',
  LAL: 'Lookalike (1-3%)',
  CUS: 'Custom Audience (Past Leads/Enrolled)',
  OPEN: 'Broad / Advantage+ Open',
  ADV: 'Advantage+ Detailed Targeting',
  DATA: 'First-Party / List Data',
  RMK: 'Retargeting (Site/Cart Visitors)',
};

export const OBJECTIVE_LABELS: Record<string, string> = {
  INSTANTFORM: 'Meta Instant Form (Native Lead Gen)',
  LP: 'Landing Page Conversion (Website)',
  CTWA: 'Click to WhatsApp (Direct Chat)',
  APPINSTALL: 'Mobile App Installs',
  VIDEO: 'Video Views / Engagement',
  SEARCH: 'Search Intent',
  PMAX: 'Performance Max',
  DISPLAY: 'Display Retargeting',
  DEMANDGEN: 'Demand Gen',
};
